name: Test Self-Hosted Runner

on:
  push:
    branches:
      - master

jobs:
  test-runner-job:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run a simple script
      run: echo "Runner is working correctly!"

    - name: List files in the repository
      run: ls -al
